"""add_blueprint_path

Revision ID: 41fb2b57db07
Revises: bdef0ebd81c8
Create Date: 2026-03-11 01:23:11.035210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41fb2b57db07'
down_revision: Union[str, Sequence[str], None] = 'bdef0ebd81c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('blueprint_path', sa.String(length=255), server_default=sa.text("'default.yaml'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifacts', 'blueprint_path')
    # ### end Alembic commands ###
